name: Export Drawio

on:
  push:
    paths:
      - 'docs/design/topology.drawio'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Export drawio to png using Docker
        run: |
          docker run -v ${{ github.workspace }}:/workdir -w /workdir jgraph/drawio -x -f png -o docs/design/topology.png docs/design/topology.drawio

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add path/to/output.png
          git commit -m "Update drawio diagram" && git push
