name: Lint CloudFormation Templates

on:
  push:
    branches:
      - main
    paths:
      - 'cloudformation/templates/*.yaml'
      - .github/workflows/lint-cf-templates.yml

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Install pydot
        run: |
          pip install pydot

      - name: Run Linter and generate DOT files
        run: |
          cfn-lint --version
          cfn-lint -g -t cloudformation/templates/*.yaml

      - name: Commit and push DOT files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cloudformation/templates/*.dot
          git commit -m "Add generated DOT graph" || echo "No changes to commit"
          git push
